### ISSUE TITLE
Add description fields to main resources

### ISSUE THREAD

**Issue by marianne-butaye** [terraform-providers/terraform-provider-bigip#121]
Hello,

There seems to be missing the 'description' field on many resources. That is a feature my team and I would be greatly interested in. 
I don't know about all the other resources, but for our part we would need it on the following resources:
- bigip_ltm_virtual_server
- bigip_ltm_pool
- bigip_ltm_pool_attachment
- bigip_ltm_node

**Comment by mdditt2000** [comment]
TER-22

**Comment by RavinderReddyF5** [comment]
@marianne-butaye 

fixed issue for 
- bigip_ltm_virtual_server
- bigip_ltm_pool
- bigip_ltm_node

there will not be any description field for "bigip_ltm_pool_attachment" it will take consider description of "bigip_ltm_pool"

**Comment by jlosito** [comment]
I've been using the new description feature, but I noticed that even though I set description = "" in the resource that the description field on the F5 still shows "VirtualServer-test". I would like the description field to be an empty string as the default.

**Comment by RavinderReddyF5** [comment]
@jlosito this issue fixed in latest code, but binary yet to release.

Similar Issue :
https://github.com/terraform-providers/terraform-provider-bigip/issues/148
